name: Test
on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop, next]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: true

      - name: Type check
        run: pnpm type-check

      - name: Build
        run: pnpm build

      - name: Test
        run: |
          pnpm test
          NODE_OPTIONS='--import=tsx/esm' pnpm run --use-node-version=18.20.3 test

      - name: Lint
        run: pnpm lint
